name: "@nickola"
title: "@nickola &mdash; Nickolay Kovalev"
description: Useful notes and snippets for different things.

copyright:
  name: Nickolay Kovalev
  link: https://github.com/nickola

markdown: kramdown

plugins:
  - jekyll-sitemap

sections:
 - Projects
 - DevOps
 - Programming
 - Tools
 - Other

collections:
  pages:
    output: true
    permalink: /:path

# Exclude from "_site"
exclude:
  - "*.code-workspace"
  - Makefile
  - static/components
  - node_modules
  - Gemfile*
  - package*.json
  - webpack*.js
