name: Knowledge Base
title: Knowledge Base &mdash; Nickolay Kovalev
description: Useful notes and snippets for different things.

copyright:
  name: Nickolay Kovalev
  link: https://github.com/nickola

markdown: kramdown

sections:
 - DevOps
 - Programming
 - Other

collections:
  pages:
    output: true
    permalink: /:path
